type WritingType = 'Q&A Essay' | 'Essay' | 'Cover Letter' | 'Interview' | 'Video Essay' | 'Statement of Purpose' | 'Letter of Motivation' | 'Statement of Objectives'

type ApplicationType = 'transfer' | 'scholarship' | 'fellowship' | 'internship' | 'competition' | 'startup' | 'graduate degree' | 'leadership' | 'hackathon' | 'research program' | 'conference' | 'mentorship' | 'facilitator'

type Social = {
    medium?: string
    dev?: string
    youtube?: string
    patreon?: string
    topmate?: string
}

type Application = {
    uid: string
    title: string
    link: string
    socials?: Social
    applicationStatus: 'in-progress' | 'rejected' | 'accepted' | 'unknown' | 'ongoing'
    writingType?: WritingType[]
    applicationType?: ApplicationType[]
    appliedYear?: string
    requiredSubscription?: 'free' | 'paid'
}

export const APPLICATIONS: Application[] = [
    {
        uid: 'application-62',
        title: 'Elite Program Software Engineering Short Q&A Essays',
        link: '/application/elite-program-software-engineering-short-qa-essays',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: '',
            topmate: '',
        },
        applicationStatus: 'rejected',
        writingType: ['Q&A Essay', 'Essay'],
        applicationType: ['scholarship', 'fellowship'],
        appliedYear: '2025',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-61',
        title: 'Hack the North 2025',
        link: '/application/hack-the-north-2025',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: '',
            topmate: '',
        },
        applicationStatus: 'ongoing',
        writingType: ['Q&A Essay'],
        applicationType: ['hackathon'],
        appliedYear: '2025',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-60',
        title: 'Adventure X 2025, Was It Fair?',
        link: '/application/adventurex-2025',
        socials: {
            medium: 'https://medium.com/@abdibrokhim/adventure-x-2025-was-it-fair-061f45585bf3',
            dev: '',
            youtube: '',
            patreon: '',
            topmate: '',
        },
        applicationStatus: 'rejected',
        writingType: ['Essay'],
        applicationType: ['hackathon'],
        appliedYear: '2025',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-59',
        title: 'PSL 2025 Cognitive Science, Statement of Objectives',
        link: '/application/psl-2025-cognitive-science-statement-of-objectives',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/collection/862594',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'unknown',
        writingType: ['Statement of Objectives'],
        applicationType: ['graduate degree'],
        appliedYear: '2025',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-0',
        title: 'Future Leaders Congress 2024 in Kuala Lumpur',
        link: '/application/future-leaders-congress-kuala-lumpur-2024',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/posts/accepted-future-111913095',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'accepted',
        writingType: ['Q&A Essay'],
        applicationType: ['scholarship', 'fellowship'],
        appliedYear: '2024',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-1',
        title: 'HPAIR 2024 Asia Conference: 2nd Stage Application Guide',
        link: '/application/hpair-2024-asia-conference-2nd-stage',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/posts/accepted-harvard-111913883',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'accepted',
        writingType: ['Q&A Essay', 'Video Essay', 'Interview'],
        applicationType: ['conference', 'scholarship', 'fellowship', 'leadership'],
        appliedYear: '2024',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-2',
        title: 'Become a UPG Sustainability Leader & Drive Global Impact',
        link: '/application/upg-sustainability-leader',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/posts/accepted-become-111913405',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'accepted',
        writingType: ['Q&A Essay'],
        applicationType: ['scholarship', 'leadership'],
        appliedYear: '2024',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-3',
        title: 'Hack the North 2024: Canada\'s Premier Hackathon Awaits',
        link: '/application/hack-the-north-2024-canada',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/posts/accepted-hack-111914002',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'accepted',
        writingType: ['Q&A Essay'],
        applicationType: ['hackathon'],
        appliedYear: '2024',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-4',
        title: 'IES at Copernicus Berlin: 2nd Stage Scholarship Application',
        link: '/application/ies-copernicus-berlin-2nd-stage',
        socials: {
            medium: '',
            dev: '',
            youtube: 'https://youtu.be/m6eWBvbf4Uk',
            patreon: 'https://www.patreon.com/posts/accepted-ies-at-111914077',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'accepted',
        writingType: ['Video Essay'],
        applicationType: ['scholarship'],
        appliedYear: '2024',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-5',
        title: 'Leaders Fellowship Maldives 2024',
        link: '/application/leaders-fellowship-maldives-2024',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/posts/accepted-leaders-111913543',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'accepted',
        writingType: ['Q&A Essay'],
        applicationType: ['leadership'],
        appliedYear: '2024',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-6',
        title: 'Ladder Student Application: Build Skills & Network',
        link: '/application/ladder-student-application',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/posts/rejected-ladder-111914199',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'rejected',
        writingType: ['Q&A Essay'],
        applicationType: ['scholarship'],
        appliedYear: '2024',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-7',
        title: 'Youth Interfaith Leaders Fellowship 2025',
        link: '/application/youth-interfaith-climate-fellowship-2025',
        socials: {
            medium: '',
            dev: '',
            youtube: 'https://youtu.be/4BPB8Cx6Ll4',
            patreon: 'https://www.patreon.com/posts/in-review-youth-111913576',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'rejected',
        writingType: ['Q&A Essay'],
        applicationType: ['scholarship', 'fellowship'],
        appliedYear: '2024',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-8',
        title: 'Hack MIT 2024: Innovate at MIT\'s Leading Hackathon',
        link: '/application/hack-mit-2024-application',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/posts/rejected-hack-111914045',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'rejected',
        writingType: ['Q&A Essay'],
        applicationType: ['hackathon'],
        appliedYear: '2024',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-9',
        title: 'World Food Forum 2024: Good Food for All',
        link: '/application/world-food-forum-2024',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/posts/unknown-world-111913443',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'unknown',
        writingType: ['Q&A Essay'],
        applicationType: ['scholarship', 'fellowship'],
        appliedYear: '2024',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-10',
        title: 'IRENA Youth Forum: Pioneering Renewable Energy Leadership',
        link: '/application/irena-youth-forum',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/posts/in-review-irena-111913510',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'rejected',
        writingType: ['Q&A Essay'],
        applicationType: ['scholarship', 'fellowship', 'leadership'],
        appliedYear: '2024',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-11',
        title: 'BRB Fintech Hackcelerator: 2nd Round Application',
        link: '/application/brb-fintech-hackcelerator-2nd-round',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/collection/862594',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'rejected',
        writingType: ['Q&A Essay'],
        applicationType: ['hackathon'],
        appliedYear: '2024',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-12',
        title: 'Headstarter Fellowship & Accelerator',
        link: '/application/headstarter-fellowship-accelerator',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/posts/accepted-2024-111914285',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'accepted',
        writingType: ['Q&A Essay'],
        applicationType: ['fellowship', 'startup'],
        appliedYear: '2024',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-13',
        title: 'KAUST Application: Craft an Impactful Statement of Purpose',
        link: '/application/kaust-application-sop',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/posts/rejected-of-vsrp-111914325',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'rejected',
        writingType: ['Statement of Purpose'],
        applicationType: ['research program'],
        appliedYear: '2024',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-14',
        title: 'OECD Internship Cover Letter',
        link: '/application/oecd-internship-cover-letter',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/posts/rejected-oecd-111914383',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'rejected',
        writingType: ['Cover Letter'],
        applicationType: ['internship'],
        appliedYear: '2024',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-15',
        title: 'Scale AI Software Engineering Intern 2025',
        link: '/application/scale-ai-intern-2025-cover-letter',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/posts/unknown-software-111914522',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'unknown',
        writingType: ['Cover Letter'],
        applicationType: ['internship'],
        appliedYear: '2024',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-16',
        title: '2024 Central Asia & Türkiye Youth Talks',
        link: '/application/central-asia-turkiye-youth-talks-2024',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/posts/unknown-central-111913650',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'rejected',
        writingType: ['Q&A Essay'],
        applicationType: ['leadership'],
        appliedYear: '2024',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-17',
        title: 'Business Today\'s 50th International Conference',
        link: '/application/business-today-50th-international-conference',
        socials: {
            medium: '',
            dev: '',
            youtube: 'https://youtu.be/bZRPy2pv2BM',
            patreon: 'https://www.patreon.com/posts/rejected-today-111913681',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'rejected',
        writingType: ['Q&A Essay'],
        applicationType: ['leadership'],
        appliedYear: '2024',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-18',
        title: 'KAIST EE Summer Program Application: Study in South Korea',
        link: '/application/kaist-summer-program-application',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/posts/rejected-kaist-111914566',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'rejected',
        writingType: ['Q&A Essay'],
        applicationType: ['scholarship', 'research program'],
        appliedYear: '2024',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-19',
        title: '778 Foundation Startup Application: Fuel Your Venture',
        link: '/application/778-foundation-startup-application',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/posts/rejected-778-111914903',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'rejected',
        writingType: ['Q&A Essay'],
        applicationType: ['scholarship', 'startup'],
        appliedYear: '2024',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-20',
        title: 'Yandex Internship',
        link: '/application/yandex-intern-application',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/collection/862594',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'accepted',
        writingType: ['Q&A Essay'],
        applicationType: ['internship'],
        appliedYear: '2024',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-21',
        title: 'VISA Interview Questions: My Real & Honest Experience. Buildspace Nights&Weekends s5 IRL Event',
        link: '/application/visa-interview-prep-questions',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/posts/irl-usa-visa-111920861',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'rejected',
        writingType: ['Q&A Essay'],
        applicationType: ['conference'],
        appliedYear: '2024',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-22',
        title: 'Next Shift Learning: Snap Engineering Academy 2024',
        link: '/application/snap-engineering-academy-2024',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/posts/rejected-next-111921197',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'rejected',
        writingType: ['Q&A Essay'],
        applicationType: ['internship', 'research program'],
        appliedYear: '2024',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-23',
        title: 'MrBeast Data Analyst Application',
        link: '/application/mrbeast-data-analyst-application',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/posts/rejected-mrbeast-111921316',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'unknown',
        writingType: ['Cover Letter'],
        applicationType: ['internship'],
        appliedYear: '2024',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-24',
        title: 'HPAIR 2024 Asia Conference: 1st Stage Application',
        link: '/application/hpair-2024-asia-conference-1st-stage',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/posts/accepted-harvard-111913825',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'accepted',
        writingType: ['Q&A Essay', 'Video Essay', 'Interview'],
        applicationType: ['conference', 'scholarship', 'fellowship', 'leadership'],
        appliedYear: '2024',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-25',
        title: 'Yale Transfer Essays',
        link: '/application/yale-transfer-essays',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/posts/rejected-yale-111921391',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'rejected',
        writingType: ['Q&A Essay'],
        applicationType: ['transfer'],
        appliedYear: '2024',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-26',
        title: 'Cognition of Language Lab Application',
        link: '/application/cognition-of-language-lab-application',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/posts/accepted-to-join-111921568',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'unknown',
        writingType: ['Cover Letter'],
        applicationType: ['internship', 'research program'],
        appliedYear: '2024',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-27',
        title: 'Notion Cover Letter Software Engineering Position',
        link: '/application/notion-software-engineer-cover-letter',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/posts/unknown-notion-111921680',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'rejected',
        writingType: ['Cover Letter'],
        applicationType: ['internship'],
        appliedYear: '2024',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-28',
        title: 'Lex Fridman Application Python Programmer',
        link: '/application/lex-fridman-python-programmer-application',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/posts/unknown-lex-2024-111921814',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'rejected',
        writingType: ['Q&A Essay'],
        applicationType: ['internship'],
        appliedYear: '2024',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-29',
        title: 'Catalyst Program Application',
        link: '/application/catalyst-program-application',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/posts/rejected-2024-111913724',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'rejected',
        writingType: ['Q&A Essay'],
        applicationType: ['internship'],
        appliedYear: '2024',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-30',
        title: 'Generative AI Accelerator',
        link: '/application/generative-ai-accelerator-application',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/posts/accepted-ai-2024-111922081',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'rejected',
        writingType: ['Q&A Essay'],
        applicationType: ['internship'],
        appliedYear: '2024',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-31',
        title: 'Entrepreneur First Application',
        link: '/application/entrepreneur-first-application',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/posts/rejected-first-111922166',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'rejected',
        writingType: ['Q&A Essay'],
        applicationType: ['internship'],
        appliedYear: '2024',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-32',
        title: 'Tufts Transfer Application: Elevate Your Academic Journey',
        link: '/application/tufts-transfer-application',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/posts/rejected-tufts-111922316',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'rejected',
        writingType: ['Q&A Essay'],
        applicationType: ['transfer'],
        appliedYear: '2024',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-33',
        title: 'University of Chicago Transfer: Tips for a Standout Application',
        link: '/application/university-of-chicago-transfer-application',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/posts/rejected-of-2024-111922398',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'rejected',
        writingType: ['Q&A Essay'],
        applicationType: ['transfer'],
        appliedYear: '2024',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-34',
        title: 'USC Transfer Essays',
        link: '/application/usc-transfer-application-essays',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/posts/rejected-usc-111922547',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'rejected',
        writingType: ['Q&A Essay'],
        applicationType: ['transfer'],
        appliedYear: '2024',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-35',
        title: 'Cornell University Transfer',
        link: '/application/cornell-transfer-application',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/posts/rejected-cornell-111922633',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'rejected',
        writingType: ['Q&A Essay'],
        applicationType: ['transfer'],
        appliedYear: '2024',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-36',
        title: 'YC Internships, Cold Cover Letters & Emails',
        link: '/application/yc-internships-cold-cover-letters',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/posts/got-offer-y-cold-111922748',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'rejected',
        writingType: ['Cover Letter'],
        applicationType: ['internship'],
        appliedYear: '2024',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-37',
        title: 'Neurolink Application Cover Letter',
        link: '/application/neurolink-application-cover-letter',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/posts/unknown-2024-111923270',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'rejected',
        writingType: ['Cover Letter'],
        applicationType: ['internship'],
        appliedYear: '2024',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-38',
        title: 'Upwork Cover Letter Template',
        link: '/application/upwork-cover-letter-template',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/posts/landed-10-upwork-111923455',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'ongoing',
        writingType: ['Cover Letter'],
        applicationType: ['competition'],
        appliedYear: '2024',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-39',
        title: 'Uzum Internship Q&A Application',
        link: '/application/uzum-internship-qna-application',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/collection/862594',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'accepted',
        writingType: ['Q&A Essay'],
        applicationType: ['internship'],
        appliedYear: '2024',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-40',
        title: 'OIST Research Internship Application',
        link: '/application/oist-research-internship-application',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/posts/in-review-oist-111924103',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'rejected',
        writingType: ['Q&A Essay'],
        applicationType: ['internship', 'research program'],
        appliedYear: '2024',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-41',
        title: 'HPAIR Harvard Conference 2025: Scholarship Application',
        link: '/application/hpair-2025-harvard-conference-scholarship',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/posts/accepted-hpair-116012451',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'accepted',
        writingType: ['Q&A Essay', 'Video Essay', 'Interview'],
        applicationType: ['conference', 'scholarship', 'fellowship', 'leadership'],
        appliedYear: '2025',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-42',
        title: 'Application to the 2025 cohort of Knight-Hennessy Scholars at Stanford University',
        link: '/application/knight-hennessy-scholars-2025-application',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/posts/in-review-2025-116012586',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'unknown',
        writingType: ['Q&A Essay', 'Cover Letter'],
        applicationType: ['graduate degree', 'scholarship'],
        appliedYear: '2025',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-43',
        title: 'The Earth Prize Facilitator\'s Community of Practice Application Form',
        link: '/application/earth-prize-facilitator-application',
        socials: {
            medium: '',
            dev: '',
            youtube: 'https://youtu.be/mj0H4EiCIr0',
            patreon: 'https://www.patreon.com/posts/accepted-earth-116013616q',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'accepted',
        writingType: ['Video Essay', 'Q&A Essay', 'Interview'],
        applicationType: ['conference', 'scholarship', 'mentorship', 'leadership', 'facilitator'],
        appliedYear: '2025',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-44',
        title: 'DAAD Letter of Motivation',
        link: '/application/daad-letter-of-motivation',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/posts/in-review-letter-116012179',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'rejected',
        writingType: ['Letter of Motivation'],
        applicationType: ['graduate degree', 'scholarship'],
        appliedYear: '2025',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-45',
        title: 'Shape the Future Challenge 2025, Moonshot Pirates',
        link: '/application/shape-the-future-challenge-moonshot-pirates',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/posts/accepted-shape-116012281',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'accepted',
        writingType: ['Q&A Essay'],
        applicationType: ['competition', 'hackathon'],
        appliedYear: '2025',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-46',
        title: '2025 Young Leaders Fellowship',
        link: '/application/2025-young-leaders-fellowship',
        socials: {
            medium: '',
            dev: '',
            youtube: 'https://youtu.be/PF6yA1hM6xM',
            patreon: 'https://www.patreon.com/posts/in-review-2025-116011649',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'rejected',
        writingType: ['Q&A Essay'],
        applicationType: ['conference', 'scholarship', 'fellowship', 'leadership'],
        appliedYear: '2025',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-47',
        title: 'IES at Copernicus Berlin: Stages 3 & 4 Scholarship Application',
        link: '/application/ies-copernicus-berlin-stage-3-and-4',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/posts/accepted-ies-at-116010968',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'rejected',
        writingType: ['Q&A Essay', 'Interview'],
        applicationType: ['conference', 'scholarship', 'fellowship', 'leadership'],
        appliedYear: '2025',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-48',
        title: 'Young Professional Internships Program 2025',
        link: '/application/young-professional-internships-program',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/collection/862594',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'unknown',
        writingType: ['Essay'],
        applicationType: ['internship'],
        appliedYear: '2025',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-49',
        title: 'f.inc Founders Application',
        link: '/application/founders-application-finc',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/collection/862594',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'rejected',
        writingType: ['Q&A Essay'],
        applicationType: ['startup'],
        appliedYear: '2025',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-50',
        title: 'AI Action Summit 2025 in France: CoMedAI (by CoMed)',
        link: '/application/ai-action-summit-2025-france-comed',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/collection/862594',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'rejected',
        writingType: ['Q&A Essay'],
        applicationType: ['startup'],
        appliedYear: '2025',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-51',
        title: 'YC Winter 2025 Application: PaperAI',
        link: '/application/yc-w2025-paper-ai-application',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/collection/862594',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'rejected',
        writingType: ['Q&A Essay'],
        applicationType: ['startup'],
        appliedYear: '2025',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-52',
        title: '8th Zhongguancun Tech Competition: Overseas Application',
        link: '/application/zhongguancun-tech-competition-8th',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/collection/862594',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'unknown',
        writingType: ['Q&A Essay'],
        applicationType: ['startup'],
        appliedYear: '2025',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-53',
        title: 'AI Action Summit 2025 France: PaperAI',
        link: '/application/ai-action-summit-2025-france-paper-ai',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/collection/862594',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'rejected',
        writingType: ['Q&A Essay'],
        applicationType: ['startup'],
        appliedYear: '2025',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-54',
        title: 'Paper AI Tools Competition: Drive Data Innovation',
        link: '/application/paper-ai-tools-competition',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/collection/862594',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'rejected',
        writingType: ['Q&A Essay'],
        applicationType: ['startup'],
        appliedYear: '2025',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-55',
        title: 'Seeds for the Future: Global Ambassador Election',
        link: '/application/seeds-for-the-future-ambassador',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/collection/862594',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'rejected',
        writingType: ['Interview'],
        applicationType: ['conference', 'scholarship', 'fellowship', 'leadership'],
        appliedYear: '2025',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-56',
        title: 'YC X2025 Application: Open Community',
        link: '/application/yc-x2025-open-community',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/collection/862594',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'rejected',
        writingType: ['Q&A Essay'],
        applicationType: ['startup'],
        appliedYear: '2025',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-57',
        title: 'YC Summer 2024: CoMed',
        link: '/application/yc-s2024-comed-application',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/collection/862594',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'rejected',
        writingType: ['Q&A Essay'],
        applicationType: ['startup'],
        appliedYear: '2025',
        requiredSubscription: 'free'
    },
    {
        uid: 'application-58',
        title: 'Artificial Intelligence in Health Competition, TEKNOFEST 2025',
        link: '/application/artificial-intelligence-in-health-competition-teknofest-2025',
        socials: {
            medium: '',
            dev: '',
            youtube: '',
            patreon: 'https://www.patreon.com/collection/862594',
            topmate: 'https://topmate.io/abdibrokhim/1324206',
        },
        applicationStatus: 'unknown',
        writingType: ['Q&A Essay', 'Essay'],
        applicationType: ['competition'],
        appliedYear: '2025',
        requiredSubscription: 'paid'
    },
]