export const NAME = "abdibrokhim"
export const IMAGE_URL = "/images/abdibrokhim.jpeg"
export const WEBSITE_URL = 'https://yaps.gg'
export const SUBSCRIPTION_URL = "https://www.patreon.com/abdibrokhim/membership"
export const REPO_URL_FORK = "https://github.com/abdibrokhim/yaps.gg-shadcnui/fork"
export const REPO_URL_STAR = "https://github.com/abdibrokhim/yaps.gg-shadcnui"
export const EMAIL_URL = "abdibrokhim@gmail.com"
export const EMAIL_URL_LINK = "mailto:abdibrokhim@gmail.com"
export const BOOK_A_CALL_URL = "https://cal.com/abdibrokhim"
export const LINKEDIN_URL = "https://www.linkedin.com/in/abdibrokhim/"
export const X_URL = "https://x.com/abdibrokhim"
export const INSTAGRAM_URL = "https://www.instagram.com/yaps.gg"
export const TELEGRAM_URL = "https://t.me/abdibrokhim"
export const YOUTUBE_URL = "https://www.youtube.com/@yapsdotgg"
export const PATREON_URL = "https://www.patreon.com/abdibrokhim"

// crypto
export const SOLANA_ADDRESS = "Fwn7y1geSEQbAUgc5hGUaB72FuPMpSNZKzfNyLwDxgzH"
export const BITCOIN_ADDRESS = "bc1qpylxaqwapk0tgdmpnnljj545z4lk2z9q5us6p6"
export const ETHEREUM_ADDRESS = "0xb4a8e71d82e8Bf84a02C7770585F9cD8b267aDB9"
export const TETHER_ADDRESS = "0xb4a8e71d82e8Bf84a02C7770585F9cD8b267aDB9"
export const BINANCE_ADDRESS = "0xb4a8e71d82e8Bf84a02C7770585F9cD8b267aDB9"