export type Hackathon = {
    winner: 'winner' | 'loser' | 'finalist' | 'in-progress' | 'honorable-mention' | 'unknown'
    prize?: string
}

export type Thing = {
    uid: string
    title: string
    description?: string
    link: string
    url?: string
    cover: string
    youtube?: string
    tutorial?: string
    github?: string
    hackathon?: Hackathon
}

export const THINGS: Thing[] = [
    {
        uid: 'thing--2',
        title: 'Douaa',
        description: 'The first open-source AI Agent for OLX.',
        link: '/thing/douaa',
        url: 'https://douaa.vercel.app/',
        cover: 'https://raw.githubusercontent.com/abdibrokhim/cover-images/main/douaa.png',
        youtube: 'https://youtu.be/ymKp6GYGPy8?si=_3YYf2oZmNMhYBK1',
        github: 'https://github.com/abdibrokhim/douaa',
        hackathon: {
            winner: 'winner',
            prize: '$150',
        },
    },
    {
        uid: 'thing--1',
        title: 'Zarin',
        description: 'Zarin is a free, open-source AI chat app with multi-model support. Powered by AI/ML API.',
        link: '/thing/zarin',
        url: 'https://zarin.vercel.app/',
        cover: 'https://raw.githubusercontent.com/abdibrokhim/cover-images/main/zarin.png',
        youtube: 'https://youtu.be/thQqVQqt-og?si=3xJN8griWrhUxpG7',
        github: 'https://github.com/abdibrokhim/zarin',
    },
    {
        uid: 'thing-0',
        title: '.env',
        description: 'touch grass alternative | viral productivity app.',
        link: '/thing/take-trash',
        url: 'https://yaps.gg/thing/take-trash',
        cover: 'https://raw.githubusercontent.com/abdibrokhim/cover-images/main/48.png',
        youtube: 'https://www.youtube.com/watch?v=jh4Tf1nSteM',
        github: 'https://github.com/abdibrokhim/Plant-Tree',
        hackathon: {
            winner: 'loser',
        },
    },
    {
        uid: 'thing-1',
        title: 'st[ate]less',
        description: 'Writing app that will delete everything if you stop typing.',
        link: '/thing/stateless',
        url: 'https://stateless.vercel.app',
        cover: 'https://raw.githubusercontent.com/abdibrokhim/cover-images/main/47.png',
        youtube: 'https://youtu.be/GSJxw_zi20w?si=mYWgIVluEj6rqNbK',
        github: 'https://github.com/abdibrokhim/stateless',
    },
    {
        uid: 'thing-2',
        title: 'yaps[dot]chat',
        description: 'one-time end-to-end encrypted anonymous chats.',
        link: '/thing/yaps-dot-chat',
        url: 'https://yaps.chat',
        cover: 'https://raw.githubusercontent.com/abdibrokhim/cover-images/main/43.png',
        youtube: 'https://youtu.be/hGyeKbRZFM8?si=gcO9LvOgOZQXVihh',
        github: 'https://github.com/abdibrokhim/yaps.chat-with-prompt-kit',
    },
    {
        uid: 'thing-3',
        title: 'notlink',
        description: 'Free open source blazingly fast url shortener ever.',
        link: '/thing/notlink',
        url: 'https://notl.ink',
        cover: 'https://raw.githubusercontent.com/abdibrokhim/cover-images/main/24.png',
        youtube: 'https://youtu.be/ahZV6aAdnVI?si=veM61ck14Y0UgFmR',
        github: 'https://github.com/abdibrokhim/notlink',
        tutorial: '/tutorial/rust-url-shortener-shuttle',
        hackathon: {
            winner: 'winner',
            prize: '$600',
        },
    },
    {
        uid: 'thing-4',
        title: 'yaps.lol (formerly lovido.lol)',
        description: 'Free open source loom video downloader.',
        link: '/thing/yaps-lol',
        url: 'https://yaps.lol',
        cover: 'https://raw.githubusercontent.com/abdibrokhim/cover-images/main/49.png',
        youtube: 'https://www.youtube.com/watch?v=bGa2Y3kO4P8',
        github: 'https://github.com/abdibrokhim/loom-dl-web'
    },
    {
        uid: 'thing-51',
        title: 'yaps music',
        description: 'playing random tracks from youtube',
        link: '/thing/yaps-music',
        url: 'https://yapsmusic.vercel.app',
        cover: '',
        youtube: 'https://www.youtube.com/watch?v=bGa2Y3kO4P8',
        github: 'https://github.com/abdibrokhim/yaps.music'
    },
    {
        uid: 'thing-5',
        title: 'Just Make Things',
        description: 'Make minimalistic cover images for your projects.',
        link: '/thing/just-make-things',
        url: 'https://justmakethings.cc',
        cover: '',
        youtube: 'https://www.youtube.com/watch?v=Qs1gdeOnPdI',
        github: 'https://github.com/abdibrokhim/justmakethings',
    },
    {
        uid: 'thing-6',
        title: 'notgrep',
        description: 'Code search made super fast. Effortlessly search for code, files, and paths across my repositories.',
        link: '/thing/notgrep',
        url: 'https://notgrep.app',
        cover: '',
        github: 'https://github.com/abdibrokhim/notgrep',
    },
    {
        uid: 'thing-7',
        title: 'Open Notes',
        description: 'Quote your favorite phrase(s) on Open Notes.',
        link: '/thing/open-notes',
        url: 'https://openotes.vercel.app',
        cover: '',
        github: 'https://github.com/abdibrokhim/2025-stickies',
    },
    {
        uid: 'thing-8',
        title: 'Back90s',
        description: 'Platform that transforms modern websites into authentic 90s-style designs while preserving core functionality.',
        link: '/thing/back90s',
        cover: '',
        youtube: 'https://www.youtube.com/watch?v=QzuHMTORsB8',
        tutorial: '/tutorial/90s-style-website-transformation',
        github: 'https://github.com/abdibrokhim/neuronostalgia-hack24',
        hackathon: {
            winner: 'winner',
            prize: '$600',
        },
    },
    {
        uid: 'thing-9',
        title: 'The Real Open Community ($TROC)',
        description: 'Empowering Open Source AI with $TROC',
        link: '/thing/troc',
        cover: '',
        github: 'https://github.com/theopencommunity',
    },
    {
        uid: 'thing-10',
        title: 'chill receipt',
        description: 'this is just a fun project. you can draw on my chill receipt. kinda imagine me as you want.',
        link: '/thing/chill-receipt',
        url: 'https://chill-receipt.vercel.app/',
        cover: '',
        youtube: 'https://youtu.be/X1zcYETM2fw?si=u7C-9F735-lLt7WN',
        github: 'https://github.com/abdibrokhim/chill-app',
    },
    {
        uid: 'thing-11',
        title: 'Embed & Visualize SFTF24 fellows in 3d space using ThreeJS',
        description: 'i simply embed all of us and visualize in 3d space; now you can know, who is your close friend and not.',
        link: '/thing/sftf24',
        url: 'https://sftf24.vercel.app/',
        cover: '',
        youtube: 'https://www.youtube.com/watch?v=CPGIUHaojVI',
        github: 'https://github.com/abdibrokhim/sftf24-table-viz'
    },
    {
        uid: 'thing-12',
        title: 'CoMedAI',
        description: 'The open source autonomous AI brain MRI analysis & diagnosis platform for doctors to help their patients.',
        link: '/thing/comedai',
        url: 'https://comedai.vercel.app/',
        cover: '',
        youtube: 'https://www.youtube.com/watch?v=-umYRToyuQ4',
        github: 'https://github.com/abdibrokhim/CoMed-web',
        hackathon: {
            winner: 'winner',
            prize: '$xxxxxx',
        },
    },
    {
        uid: 'thing-13',
        title: 'PaperAI',
        description: 'The open source collaborative AI research platform.',
        link: '/thing/paperai',
        url: 'https://paperai.pro/',
        cover: '',
        youtube: 'https://www.youtube.com/watch?v=E7d1rLyXXVE',
        tutorial: '/tutorial/ai-sticker-maker-nextjs',
        github: 'https://github.com/abdibrokhim/paper-ai-voice-assistant',
        hackathon: {
            winner: 'winner',
            prize: '$1600',
        },
    },
    {
        uid: 'thing-14',
        title: 'PrepAlly',
        description: 'The open-source AI coding prep platform, offering real-time feedback, voice-guided insights, and secure, interactive practice.',
        link: '/thing/prepally',
        cover: '',
        youtube: 'https://www.youtube.com/watch?v=wyp8tRTLLfQ',
        tutorial: '/tutorial/ai-coding-interviewer-startup',
        github: 'https://github.com/abdibrokhim/ai-coding-interviewer',
        hackathon: {
            winner: 'honorable-mention',
        },
    },
    {
        uid: 'thing-15',
        title: 'HumanAIze',
        description: 'HumanAIze AI text with the smartest AI humanizer.',
        link: '/thing/humanize',
        url: 'https://humanaize.vercel.app/',
        cover: '',
        youtube: 'https://www.youtube.com/watch?v=CLrENdjIe58',
        tutorial: '/tutorial/ai-text-humanizer-nextjs',
        github: 'https://github.com/abdibrokhim/humanaize',
        hackathon: {
            winner: 'winner',
            prize: '$1000',
        },
    },
    {
        uid: 'thing-16',
        title: 'AI Sticker Maker',
        description: 'In just seconds, you can effortlessly transform your ideas into custom stickers.',
        link: '/thing/ai-sticker-maker',
        url: 'https://ai-sticker-maker.vercel.app/',
        cover: '',
        tutorial: '/tutorial/ai-sticker-maker-nextjs',
        github: 'https://github.com/abdibrokhim/ai-sticker-maker',
    },
    {
        uid: 'thing-17',
        title: 'NextGen o1',
        description: 'NextGen o1 overcomes the limitations of the OpenAI o1 model by adding critical functionalities.',
        link: '/thing/ai-sticker-maker',
        url: 'https://ai-sticker-maker.vercel.app/',
        cover: '',
        youtube: 'https://youtu.be/_wTaMLL4by0',
        tutorial: '/tutorial/chat-with-pdf-pinecone',
        github: 'https://github.com/abdibrokhim/nextgen-o1',
        hackathon: {
            winner: 'loser',
        },
    },
    {
        uid: 'thing-18',
        title: 'MonkeytypeAI',
        description: 'A minimalistic and customizable AI-powered typing test.',
        link: '/thing/monkeytypeai',
        url: 'https://monkeytypeai.vercel.app/',
        cover: '',
        youtube: 'https://youtu.be/SGibxV1YHDo',
        github: 'https://github.com/abdibrokhim/monkeytype-ai',
        hackathon: {
            winner: 'winner',
            prize: '$600',
        },
    },
    {
        uid: 'thing-19',
        title: 'LangflowAI',
        description: 'We automate Langflow with AI. No more drag and drop. Simply dictate and AI gets the work done!',
        link: '/thing/langflowai',
        url: 'https://langflow-4fi8.onrender.com/',
        cover: '',
        youtube: 'https://youtu.be/d9eJJHAp8v8',
        github: 'https://github.com/abdibrokhim/langflow',
        hackathon: {
            winner: 'winner',
            prize: '$800',
        },
    },
    {
        uid: 'thing-20',
        title: 'StoryAI',
        description: 'StoryAI presents climate change data in a story format that can be generated according to the user\'s interests and level of academic knowledge in the field.',
        link: '/thing/storyai',
        url: 'https://chatgpt.com/g/g-PRa3ZXK36-story-ai',
        cover: '',
        youtube: 'https://youtu.be/-IPLUUTiZak',
        github: 'https://github.com/abdibrokhim/story-ai-chrome-extension',
        hackathon: {
            winner: 'winner',
            prize: '$500',
        },
    },
    {
        uid: 'thing-21',
        title: 'EcoShopAI',
        description: 'EcoShopAI is a Chrome extension that helps you find eco-friendly products and reduce your carbon footprint.',
        link: '/thing/ecoshopai',
        url: 'https://chatgpt.com/g/g-rTTibE8p9-ecoshop-ai',
        cover: '',
        youtube: 'https://youtu.be/8GTJseYt7TA',
        hackathon: {
            winner: 'unknown',
        },
    },
    {
        uid: 'thing-22',
        title: 'AI Magic Flashcards',
        description: 'Generate flashcards simple invoke your imagination. Guess others flashcards and earn points. Exchange points to extra flashcard generations or cash them out (soon).',
        link: '/thing/aimagicflashcards',
        url: 'https://ai-magic-flashcards.vercel.app/',
        cover: '',
        youtube: 'https://youtu.be/1NcGAoXCouM',
        github: 'https://github.com/abdibrokhim/AI-Magic-FlashCards-with-Stripe',
    },
    {
        uid: 'thing-23',
        title: 'Chat With PDF',
        description: 'Join millions of students, researchers and professionals to instantly answer questions and understand research with AI.',
        link: '/thing/chatwithpdf',
        url: 'https://crunchgpt.vercel.app/',
        cover: '',
        youtube: 'https://youtu.be/AAy8ejtgBh4',
        github: 'https://github.com/abdibrokhim/Chat-With-PDF-NextJS-Langchain-Pinecone-OpenAI',
    },
    {
        uid: 'thing-24',
        title: "Harmony Quest",
        description: "Harmony Quest is an engaging multiplayer game that combines creativity, guessing, and social interaction.",
        link: '/thing/harmony-quest',
        cover: '',
        youtube: "https://youtu.be/6opWWYy7yos",
        github: "https://github.com/abdibrokhim/aiio",
        hackathon: {
            winner: 'loser',
        },
    },
    {
        uid: 'thing-25',
        title: "MeWellAI",
        description: "MeWellAI is an AI-powered mobile application designed to revolutionize mental wellness support by combining the familiarity of social media with personalized mental health assistance.",
        link: '/thing/mewellai',
        cover: '',
        youtube: "https://youtu.be/eTCg3pfm69o",
        github: "https://github.com/abdibrokhim/mentalwellness",
        hackathon: {
            winner: 'winner',
            prize: '$300',
        },
    },
    {
        uid: 'thing-26',
        title: "Personal Website",
        description: "I would highly encourage you to visit my personal website at abdibrokhim.vercel.app. I fully redesigned it.",
        link: '/thing/personal-website',
        url: 'https://abdibrokhim.vercel.app/',
        cover: '',
    },
    {
        uid: 'thing-27',
        title: "Pantry Tracker",
        description: "Pantry Tracker as part of Headstarter Software Engineering Fellowship.",
        link: '/thing/pantry-tracker',
        url: 'https://pantry-tracker-ai.vercel.app/',
        cover: '',
        youtube: "https://youtu.be/YSgSCvTrcFU?si=fx40SVo8YBIFpqh9",
        github: "https://github.com/abdibrokhim/pantry-tracker",
    },
    {
        uid: 'thing-28',
        title: "Alert ME",
        description: "Alert ME is a geolocation reporting app for the safety of users.",
        link: '/thing/alert-me',
        cover: '',
        github: "https://github.com/abdibrokhim/Flutter-Send-Location-via-SMS",
    },
    {
        uid: 'thing-29',
        title: "ChatGPT Rust Desktop App",
        description: "Open Source implementation of ChatGPT Desktop application written in TypeScript and React using Next.js, and Rust using Tauri.",
        link: '/thing/chatgpt-rust-desktop-app',
        url: '',
        cover: '',
        github: "https://github.com/abdibrokhim/ChatGPT4-Rust-Desktop-App",
    },
    {
        uid: 'thing-30',
        title: "GPT Hub",
        description: "Versatile GPT Solutions for your Business",
        link: '/thing/gpt-hub',
        url: 'https://gpthubai.vercel.app/',
        cover: '',
    },
    {
        uid: 'thing-31',
        title: "WeShot",
        description: "Welcome to WeShot, the ultimate social media haven where your moments aren't just shared, they're celebrated.",
        link: '/thing/weshot',
        url: 'https://weshot.vercel.app/',
        cover: '',
        youtube: "https://youtu.be/GjeXKXisffQ?si=h1f-Ox6lo8a1wRa4",
        github: "https://github.com/abdibrokhim/weshot",
        hackathon: {
            winner: 'loser',
        },
    },
    {
        uid: 'thing-32',
        title: "ChatGPT mobile app",
        description: "Simple ChatGPT mobile app implementation using Flutter framework and Dart programming language. Supports all OpenAI LLMs via API.",
        link: '/thing/chatgpt-mobile-app',
        cover: '',
        github: "https://github.com/abdibrokhim/ChatGPT3.5-Flutter-App",
    },
    {
        uid: 'thing-33',
        title: "Debt tracker",
        description: "Simple implementation of Debts tracker from different shops and markets.",
        link: '/thing/chatgpt-mobile-app',
        cover: '',
        github: "https://github.com/abdibrokhim/qarzsiz",
    },
    {
        uid: 'thing-34',
        title: "Flutter Cohere package",
        description: "This package provides a powerful bridge between your Flutter application and Cohere AI.",
        link: '/thing/flutter-cohere-package',
        url: 'https://pub.dev/packages/flutter_cohere',
        cover: '',
        github: "https://github.com/abdibrokhim/flutter_cohere",
    },
    {
        uid: 'thing-35',
        title: "OpenVoice API",
        description: "Free AI voice cloning API implementation. Now Open Source.",
        link: '/thing/openvoice-api',
        cover: '',
        github: "https://github.com/abdibrokhim/OpenVoice-API",
    },
    {
        uid: 'thing-36',
        title: "Truck ReportMe",
        description: "Truck ReportMe is an App that Automates Truck Reports in Logistics. ",
        link: '/thing/truck-reportme',
        cover: '',
        youtube: "https://youtu.be/9luZH0NjcR4?si=BFUbLOhl6wseBJ4t",
        github: "https://github.com/abdibrokhim/monday.com-flutter-app-for-lgstcs",
    },
    {
        uid: 'thing-37',
        title: "Truck Simulator",
        description: "Truck ReportMe is an App that Automates Truck Reports in Logistics. ",
        link: '/thing/openvoice-api',
        cover: '',
        github: "https://github.com/abdibrokhim/TuckSimulator-unity",
    },
    {
        uid: 'thing-38',
        title: "Telegram Group Users Scraper",
        description: "Telegram Group Users Scraper is a Python script that scrapes users from a Telegram group using the Telethon library.",
        link: '/thing/telegram-group-users-scraper',
        cover: '',
        github: "https://github.com/abdibrokhim/telethon-scraper",
    },
    {
        uid: 'thing-39',
        title: "BeatSaber VR Game",
        description: "I tried to repeat BeatSaber VR Game using Unity. This was final University project, that got one of the highest marks.",
        link: '/thing/beat-saber-vr-game',
        cover: '',
        github: "https://github.com/abdibrokhim/BeatSaber-VR-Game",
    },
    {
        uid: 'thing-40',
        title: "Monday.com AI Assistant",
        description: "Monday.com native Web application (VSCode clone) that allows to run queries instantly. Now, you don't need to open Postman or Code editor to make queries to Monday.com API.",
        link: '/thing/monday-ai-assistant',
        cover: '',
        github: "https://github.com/abdibrokhim/monday.com-ai-assistant-hackathon",
        hackathon: {
            winner: 'loser',
        },
    },
    {
        uid: 'thing-41',
        title: "YTShorts",
        description: "An App where everyone can generate YouTube shorts or even long Videos in seconds.",
        link: '/thing/ytshorts',
        cover: '',
        github: "https://github.com/abdibrokhim/ai-mental-health",
        hackathon: {
            winner: 'loser',
        },
    },
    {
        uid: 'thing-42',
        title: "Generate & Deploy NFT's",
        description: "",
        link: '/thing/generate-deploy-nfts',
        cover: '',
        github: "https://github.com/abdibrokhim/cw3d-AlchemySDK",
        hackathon: {
            winner: 'unknown',
        },
    },
    {
        uid: 'thing-43',
        title: "ChatGPT Telegram Bot",
        description: "Comprehensive telegram bot. Built using ChatGPT API. Supports Django on backend. Has pricing options.",
        link: '/thing/chatgpt-telegram-bot',
        cover: '',
        github: "https://github.com/abdibrokhim/ChatGPT-TelegramBot",
    },
    {
        uid: 'thing-44',
        title: "Lychee",
        description: "Watching online lectures is convenient. But, makes it hard to engage with the material.",
        link: '/thing/lychee',
        cover: '',
        github: "https://github.com/abdibrokhim/Lychee",
        hackathon: {
            winner: 'loser',
        },
    },
    {
        uid: 'thing-45',
        title: "No code customer care bot",
        description: "",
        link: '/thing/no-code-customer-care-bot',
        cover: '',
        github: "https://github.com/kuv7956/projectclippy",
        hackathon: {
            winner: 'loser',
        },
    },
    {
        uid: 'thing-46',
        title: "Report Cruncher",
        description: "",
        link: '/thing/report-cruncher',
        cover: '',
        github: "https://github.com/LatVAlY/report-cruncher",
        hackathon: {
            winner: 'finalist',
        },
    },
    {
        uid: 'thing-47',
        title: "Glanz - Fashion & Beauty",
        description: "",
        link: '/thing/glanz-fashion-beauty',
        cover: '',
        github: "https://github.com/kuv7956/projectclippy",
    },
    {
        uid: 'thing-48',
        title: "Lexica Search Engine",
        description: "",
        link: '/thing/lexica-search-engine',
        url: 'https://lexica-search-engine.vercel.app/',
        cover: '',
        github: "https://github.com/abdibrokhim/The-Stable-Diffusion-Search-Engine",
    },
    {
        uid: 'thing-49',
        title: "Lil Cute Ghost Club",
        description: "",
        link: '/thing/lil-cute-ghost-club',
        url: 'https://opensea.io/collection/lilcuteghostclub',
        cover: '',
    },
    {
        uid: 'thing-50',
        title: "MOOD by LONE.Guy",
        description: "This is one of the best mixed and mastered instrumentals of mine.",
        link: '/thing/mood-by-lone-guy',
        url: 'https://soundcloud.com/loneguy/prod-by-lone-guy-mood',
        cover: '',
    },
]
